### ISSUE TITLE
Determine Python Version

### ISSUE THREAD

**Issue by Kirska** [DallasPetsAlive/ruff-portal#1]
The Python version used needs to be 100% decided upon, 2.x vs 3.x.

If using an older version, need to consider option for maintaining 3.x branch.

**Comment by Kirska** [comment]
The Google API only officially supports 2.x with no apparent intention to support 3.x.

**Comment by dhosterman** [comment]
The largest issue I'm seeing right now with using the preferred (IMO) 3.x version is that Google isn't providing direct support for their APIs in 3.x for reasons that don't seem to make any sense to anyone but them. I've found some third party libraries that seem to support 3.x, one of which I've been able to start the Oauth2 flow through via terminal.

I believe we could homebrew a method to perform the Oauth2 and just perform our calendar operations via generated REST requests, but I don't have a whole lot of experience interacting with Google's software. Anyone else done much of this?

**Comment by Kirska** [comment]
It's worth noting that there's a very good possibility we will be interfacing with more than just the calendar for future features. For example, we will want to use eventually Google as one sign in mechanism for users, especially those that belong to the dallaspetsalive.org domain (which is in Google Apps). We may sync with Google Drive for some shared files and docs, depending on how complex that ends up being. We may want to use the Maps API for some features, like events and coordinating transport.

**Comment by jpalomar** [comment]
2.7.x is still actively maintained but promises no feature enhancement -- just security patches, hence the locked minor number.  3.x continues to get feature and performance enhancements but is still slow to gain adoption hence the six years of active maintenance for 2.7.x  .  But instead, use 2.7 and write.  3.x has migration tools to help migrating to 3.4 (atm) if need be.  That was the issue of fragmentation with Python 3.  It broke compatibility with no deprecation iteration in Python 2.  Widely used dependencies -- which Python and pip has a lot of -- are open source and may be slowly maintained and migrated.  It is a huge effort to rewrite your whole framework when core statements like try-catch or print are syntactically different.  You have the option of writing in 2.7.x with a "-3" flag to help produce warnings where syntax is not supported in Python 3.  I would suggest just writing what you need to get it done.  If something requires 3.x then the project can worry about porting to 3... while 2.7.x is default on most unixy OSes that will install a default python package ( OS X, Ubuntu, Mint, FreeBSD ) it makes it easier to just run from there...

I'm unsure of why this project would need to use a google api for python.  What are the benefits?  Most of google's api for it's public products and auth token usage can be accessed from the front-end via javascript making the server render dependency mute.  Are we using google sign-in as a user account management tool?  If so there is a client-side auth process.

We should be clear -- what are the "purposes" or "tasks" of each server and client services?

**Comment by jpalomar** [comment]
I should be frank,  I see Django as a CMS (content management system) that securely serves pages to the client and handles some REST points that does CRUD operations.  I do hope we are doing most of the signed in interactions though SSL. I have a feeling that Django and its Python language is seen as the sole dynamic content provider as it was ten years ago.  I would highly recommend against that since most calculations and logic can be done client side then sent to the server when ready.  Django is a tool to provide a system of endpoints to the client application that can be fetched by browser navigation or javascript.

For instance, the old interaction of looking at slide show of pictures of dogs are
going to a "domain.com/slideshow" page to access `LIST_OF_IMGS = [ dog_img_01, dog_img_02, dog_img_03, dog_img_04, dog_img_05, etc... ]` and the CMS would respond with one of two things:
1. provide the data for each `LIST_OF_IMGS` element per page from uri queries like `slideshow?img=1` and respond with a new page from interactions with `<a>` tags for navigation to go to `#next` via `?img=1` or `#previous` via `?img=0` forcing the user to reload a new page each time to conserve bandwidth 
2. provide the whole array of images() and load the images hoping its not a lot and asynchronously load each image and worry about chunking data later... ( scale nightmare... )

Well now you can construct "domain.com/slideshow" using Django to serve the **slideshow** module's main class from `view.py` to serve the skeletal HTML.  Then have the client javascript request another view class in the Django **slideshow** module that takes a beginning index as a parameter and a range as an optional parameter that defaults to 10 or something arbitrary to return blocks of the `LIST_OF_IMGS[0-9]`, `LIST_OF_IMGS[10-19]`, etc... and then constructs the interactive elements based on the responses thus reducing the amount of processes the server has to handle and preserving the previous requests.  It also provides a more "native" experience since it doesn't feel like a series of webpages but an application on the web.  Django just relays information from the Postgres DB to the client with little to no logic.

**Comment by dhosterman** [comment]
Thanks, jpalomar.

I don't particularly care whether we decide to move toward a more client-side architecture or rely primarily on Django to serve content. I do take some exception to the suggestion that Django is only a tool to provide endpoints to Javascript or that using Django to serve content directly is outdated (if I'm understanding you; if not, my apologies).

In this case, I suggest we decide on the technology that best fits our needs and scope. I don't expect that scaling is going to be an issue, and engineering for that kind of scaling at this point is premature. Likewise, I'm not sure that providing a "native" experience is a priority at this point. Kirska will have to address those questions.

That said, if we want to use Django as just a REST service and go full-on client with *.js, that's fine. I've got some experience with Angular.js if we're interested in going with a client-side framework.

**Comment by Kirska** [comment]
I'm just happy to see meaningful discussion! Caveat: you guys know more about web technologies than I do, I'm like the stereotypical subject matter expert that knows a lot about the problem domain but not a lot about the solution technology.

_Scaling_

Scaling isn't a big concern for this project since it's only used by volunteers, not the general public, so we won't be expecting a lot of simultaneous users. The automation tasks (automatic date-based emails, etc) can be scheduled to run at off-peak hours. If we end up expanding to other organizations, then I would expect them to run the app on their own server instance, not on ours.

_JS_

I am more inclined to lean on Python for logic even if it is server side, since I feel that it will be cleaner code, easier for someone new to jump in and help, and easier to test.

I think perhaps an all or nothing approach here may not be necessary. We can always use Python for a lot of the logic, and then if there is a specific task that will have a significant user experience improvement by using JS then we can use it in that case. Image work like @jpalomar has mentioned is a good example of a case where JS may be a better approach. But for a task like event signups which is one of the first priorities, there should be very limited logic that shouldn't have a huge impact on user experience if it is run server side.

_Google API_

For some background info, we use Google **extensively** as an organization. You can blame me for that since I'm a huge fan of Google products. Google also provides us an Ad grant worth over $100,000/year, the largest grant we have as an organization by a landslide. So the organization as a whole has a vested interest in staying with Google products.

I mentioned above some the possible uses for the Google API in the future. I think this is another case where using the Python API will probably be cleaner code than using JS on the front end, but again, it's another case where if it is still clean but more efficient to use JS with REST or what not on the front end, then we can determine that on a case by case basis. I don't want to use JS across the board, generally speaking.

I am 100% sure we will use Google Calendar and Google signin. I am 60% sure we will use Maps and Docs/Drive but those features aren't a high priority so they're not fleshed out. I can see potential uses for Youtube (uploading foster videos, this is a manual process right now and a PITA), Tasks (delegating form leadership), URL Shortener (for social media team), Gmail (for group addresses and application processing), G+ (for user customization and sharing), and Translate (for our Spanish speaking fosters, we sometimes have to 3-way call with translators for basic info).

So I feel like the potential for extensive use is high enough that integrating with the API is a good exercise for the first iteration even if for specific tasks later we decide not to use it.

_Version_

I am leaning towards 2.7 right now to "just work".

Hopefully that answers the questions above.

**Comment by jpalomar** [comment]
@dhosterman I don't think of Django as _just_ a tool to serve endpoints for a sole client-side REST framework.  I believe it can be levied to be a great MVC-centric tool that securely serves pages, templates, and endpoints quickly.  It has great community support and a robust system of authentication.  I've encountered Django ecom sites that only use python to handle interactions and content loading like the old PHP and JSP set-ups.  There can be some scary spaghetti code that can happen when layout, interactions, and content is dictated by server-side systems.  Modular design has helped curve some of it but ugly things have happened when functionality and presentation do not harmonize to produce usability.

Django has a wonderful templating system that renders HTML using logic to interpret data retrieved from the Postgres DB.  I've seen it abused and a mess  -- sloppy and nested if-else statements and unnecessary loops --  where handling that data is much easier to do and maintain client-side.  I am also a fan of thin layers of APIs.  I mean thin in a way that the frameworks do not overly burden dependency.  Angular is a great tool but whole sites have built awful dependencies on Angular; it is a **HUGE** framework with its documentation could be much improved.  Recently, google has been doing surveys recently on where to improve their open source projects and documentation has been high on that list.  But I will say that they tightly integrate googley products into their api and the google supported plugins are plug'n'play.

@Kirska I agree that form submission and validation is better handled server-side.  I also don't want a JS-only site; it's a fine balance between the two sides that should compliment each other.  Integrating google auth is a great first step into deploying a site.  As for the 2.7 inclination: :+1: 

So the gh-pages is pretty much set up using Jekyll to serve rendered content.  If @dhosterman or @Kirska have any questions on how to add pages or add entries, please let me know.  If there's other things I can help with, please let me know.

**Comment by dhosterman** [comment]
Thanks for the good input, both. I've gone ahead and put up the Django project scaffolding. I've added iPython to the requirements as a development tool and Sphinx for documentation.

Django settings have been moved into their own module which makes managing multiple settings files for multiple developers much easier than the default configuration. You can create your own development settings file(s) inside the settings directory and import \* from settings.py, then override or add anything you might require for your own development process (local database credentials, etc). The base settings.py file is where all the core requirements go. I've modified that file to use environment variables for secret key and debug by preference, but to create a random secret key and have debug on if no environment variables are present.

Please let me know if you have any questions!

**Comment by Kirska** [comment]
Thanks for that commit with the scaffolding, looks great and will be a big help moving forward.

I'm going to go ahead and close this and we can open new issues for anything coming up. I think we're settled on 2.7 for now, can reopen if we want to discuss further
